version: '3'

services:
  myrecipe:
    build:
      context: .
    ports:
      - "80:8000"
    volumes:
      - .:/myrecipe
    command: >
      sh -c "python3 manage.py makemigrations &&
      python3 manage.py migrate &&
      python3 manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=postgresdb
      - DB_NAME=myrecipedb
      - DB_USER=postgresdb
      - DB_PASS=supersecretpassword
    depends_on:
      - postgresdb
  postgresdb:
    image: postgres:12.1-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=myrecipedb
      - POSTGRES_USER=postgresdb
      - POSTGRES_PASSWORD=supersecretpassword