#  Copyright (c) Code Written and Tested by Ahmed Emad in 23/03/2020, 13:54.

# Generated by Django 3.0.4 on 2020-03-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0002_auto_20200322_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, max_length=300, unique=True),
        ),
    ]
