#  Copyright (c) Code Written and Tested by Ahmed Emad in 24/03/2020, 14:36.

# Generated by Django 3.0.4 on 2020-03-23 22:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0004_recipecomment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeComment',
            new_name='RecipeReview',
        ),
    ]
