#  Copyright (c) Code Written and Tested by Ahmed Emad in 24/03/2020, 14:43.

# Generated by Django 3.0.4 on 2020-03-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('recipes', '0006_auto_20200324_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='recipereviewmodel',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
